title: "Homepage of Gert Vercleyen"
author: "Gert Vercleyen"
description: "PhD Student at Maynooth University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "home.md"}
  - {title: "Theme info", file: "README.md"}
  - {title: "Posters", "posters.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gert.vercleyen@protonmail.com"}
  - {title: Github, icon: github, url: "https://github.com/gert-vercleyen"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
